# Generated by Django 5.0.2 on 2024-03-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('applicant_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SendOtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumber', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=10)),
                ('pan_front', models.ImageField(upload_to='images/')),
                ('pan_back', models.ImageField(upload_to='images/')),
                ('aadhar_number', models.CharField(max_length=10)),
                ('aadhar_front', models.ImageField(upload_to='images/')),
                ('aadhar_back', models.ImageField(upload_to='images/')),
                ('voter_id', models.CharField(max_length=10)),
                ('voter_front', models.ImageField(upload_to='images/')),
                ('voter_back', models.ImageField(upload_to='images/')),
                ('selfie', models.ImageField(upload_to='images/')),
                ('business_type', models.CharField(max_length=100)),
                ('business_name', models.TextField()),
                ('business_address', models.TextField()),
                ('business_pic', models.ImageField(upload_to='images/')),
                ('two_wheeler', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('four_wheeler', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('own_residence', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('rented', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('life_insurance', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('credit_card', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('any_loan', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('dependent_member', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('children_academic', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('step', models.IntegerField(default=0)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.applicants')),
            ],
        ),
    ]
