# Generated by Django 5.0.2 on 2024-03-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
