# Generated by Django 5.0.2 on 2024-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_applicationverification_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationverification',
            name='aadhar_number',
            field=models.CharField(max_length=12),
        ),
    ]
