# Generated by Django 5.0.2 on 2024-03-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sendotpmodel',
            table='sendotpmodel',
        ),
    ]
