# Generated by Django 5.0.2 on 2024-03-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_applicationverification_aadhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationverification',
            name='any_loan',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applicationverification',
            name='children_academic',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applicationverification',
            name='credit_card',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applicationverification',
            name='dependent_member',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applicationverification',
            name='four_wheeler',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applicationverification',
            name='life_insurance',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applicationverification',
            name='own_residence',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applicationverification',
            name='rented',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='applicationverification',
            name='two_wheeler',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=5),
        ),
    ]
