# Generated by Django 5.0.2 on 2024-03-05 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_applicationverification_any_loan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationverification',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.applicants'),
        ),
    ]
