# Generated by Django 5.0.2 on 2024-03-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_sendotpmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicants',
            table='applicants',
        ),
        migrations.AlterModelTable(
            name='applicationverification',
            table='applicationVerification',
        ),
    ]
